---
abstract: 'An N-ary tree'
author:
  - 'Sean M. Burke <sburke@cpan.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tree-DAG_Node
provides:
  Tree::DAG_Node:
    file: lib/Tree/DAG_Node.pm
    version: '1.23'
requires:
  File::Slurp::Tiny: '0.003'
  File::Spec: '3.4'
  File::Temp: '0.19'
  strict: '0'
  warnings: '0'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '1.23'
